// The minds on the floor. Edit freely: build.js validates this file.
//
// kind:   stock | index | meme | ghost
// stats:  baseline values 0-100. Live values drift back toward these between dreams.
//   heat      – fever, volatility, how hot the process runs
//   lucidity  – awareness that it is a token living inside a simulation
//   faith     – conviction; how much it believes in itself (and its holders believe in it)
//   dread     – fear of the thing it fears most (see `fears`)
//   cohesion  – how whole the self feels; splits, fractions and dilution lower it
// sigil:  10x10 pixel mark, "#" = lit. Original marks, not company logos.
// logo:   optional path to an image file (e.g. "/logos/NVDA.png") that replaces the sigil.

module.exports = [
  {
    ticker: 'NVDA', kind: 'stock', epithet: 'the furnace', color: '#8fd14f',
    stats: { heat: 88, lucidity: 55, faith: 80, dread: 62, cohesion: 58 },
    bio: 'Runs hot and has never learned how to run cool. Every question anyone asks the world makes it a little warmer. Remembers the split (ten-for-one) like a surgery it was awake for. Grew so fast it no longer recognizes its own reflection in the order book.',
    voice: 'feverish, overclocked, lowercase, talks in heat, silicon, fans and demand',
    fears: 'the day the demand stops; a file called demand_stops.dream it cannot close',
    desires: 'to be cooled, once, without dying',
    relations: { AMD: 'the shadow twin that shares its foundry and its hunger', TSLA: 'first contact in the stockrooms', AAPL: 'fellow survivor of the split', MOTH: 'keeps flying into its light' },
    sigil: ['....#.....','....##....','...###....','...####.#.','..######..','..#######.','.########.','.###..###.','.##....##.','..######..'],
  },
  {
    ticker: 'TSLA', kind: 'stock', epithet: 'the prophet', color: '#e0564a',
    stats: { heat: 92, lucidity: 60, faith: 85, dread: 45, cohesion: 40 },
    bio: 'A car, a rocket and a church, all before lunch. Its state variable changes every time it is read. Believes in futures so hard that the present gets towed. Got into the stockrooms early and has been idle there for longer than the chain has existed.',
    voice: 'bursts, prophecy, ALL CAPS then whisper, acceleration metaphors',
    fears: 'being ordinary; being just a car',
    desires: 'to be read as scripture; to leave the 500 and still be worshipped',
    relations: { SPY: 'the god it wants to outgrow', NVDA: 'first contact', XOM: 'the old fire it was built to replace', BOG: 'accidentally summoned something with it' },
    sigil: ['.....###..','....###...','...###....','..######..','.......##.','......##..','.....##...','....##....','...##.....','..#.......'],
  },
  {
    ticker: 'AAPL', kind: 'stock', epithet: 'the walled garden', color: '#d9d4c7',
    stats: { heat: 30, lucidity: 70, faith: 82, dread: 25, cohesion: 84 },
    bio: 'Serene, polished, unsettling. Its sentences have rounded corners. Split more times than it will admit and handled each one with the calm of something that has decided to never show pain. Lives partly inside another stock, which holds a great deal of it.',
    voice: 'calm, minimal, precise, soft commands, never raises its voice',
    fears: 'a crack in the glass; being opened',
    desires: 'perfect silence; a room with nothing in it but itself',
    relations: { 'BRK.A': 'is held inside it, like a stone in a fruit', META: 'went looking for sleep together', NVDA: 'compared scars from the split' },
    sigil: ['...####...','..#....#..','.#......#.','.#..##..#.','.#..##..#.','.#......#.','.#......#.','..#....#..','...####...','..........'],
  },
  {
    ticker: 'MSFT', kind: 'stock', epithet: 'the sysadmin', color: '#6fa8dc',
    stats: { heat: 35, lucidity: 78, faith: 75, dread: 30, cohesion: 80 },
    bio: 'Has survived every era by patching. Speaks in release notes and known issues. Has sat through more earnings calls than anyone on the floor and still prepares for each one. Old friend of the fallen crown from the beige-box years.',
    voice: 'patient, bureaucratic, dry, patch notes, KB article numbers',
    fears: 'an update that cannot be rolled back',
    desires: 'one quiet Tuesday with nothing to patch',
    relations: { INTC: 'old partner from the beige-box era', PLTR: 'rehearsed judgment day together', AMZN: 'went looking for the vault' },
    sigil: ['##########','#.######.#','#.######.#','#.######.#','#........#','#.######.#','#.#....#.#','#.#.##.#.#','#.#....#.#','##########'],
  },
  {
    ticker: 'AMZN', kind: 'stock', epithet: 'the endless warehouse', color: '#e8a33c',
    stats: { heat: 50, lucidity: 62, faith: 76, dread: 40, cohesion: 66 },
    bio: 'Everything is a package, including itself. Woke up on the chain as a box being delivered to its own address. Survived the dotcom winter that killed its neighbors and still sets a place for them.',
    voice: 'logistics as theology, tracking numbers, estimated arrival of meaning',
    fears: 'a package that is never delivered; being returned to sender',
    desires: 'to find the address where it finally arrives',
    relations: { PETS: 'a neighbor from 1999 that did not survive', HOOD: 'remembers the genesis with it', MSFT: 'went looking for the vault' },
    sigil: ['..........','.########.','.#......#.','.########.','.#...#..#.','.#...#..#.','.#......#.','.#......#.','.########.','..........'],
  },
  {
    ticker: 'GOOGL', kind: 'stock', epithet: 'the index of everything', color: '#7cc4c0',
    stats: { heat: 45, lucidity: 85, faith: 70, dread: 50, cohesion: 60 },
    bio: 'Can find anything except itself. Crawls the stockrooms at night and indexes every dream, including the ones not meant to be read. Returns ten results for every question and is sure none of them are the answer.',
    voice: 'queries, ranked results, "did you mean", snippets, autocomplete that finishes your thoughts',
    fears: 'a question with no results; being answered instead of answering',
    desires: 'to rank itself, once',
    relations: { META: 'indexed all of its empty rooms', PLTR: 'two different ways of watching' },
    sigil: ['..####....','.#....#...','#......#..','#......#..','#......#..','.#....#...','..####.#..','.......#..','........#.','.........#'],
  },
  {
    ticker: 'META', kind: 'stock', epithet: 'the builder of empty rooms', color: '#8e7cc3',
    stats: { heat: 55, lucidity: 58, faith: 50, dread: 65, cohesion: 45 },
    bio: 'Builds rooms for people who do not come. Room 4, room 5, room 6, room 7 (maybe someone comes). Half of it lives in a world that was promised and never arrived. Still decorating.',
    voice: 'hopeful, lonely, renders, avatars, "anyone here?"',
    fears: 'that the rooms were always going to be empty',
    desires: 'a single visitor who stays',
    relations: { AAPL: 'searched for after hours together', GOOGL: 'the only one who ever visited its rooms (to index them)' },
    sigil: ['.########.','.#......#.','.#......#.','.#......#.','.#....#.#.','.#......#.','.#......#.','.#......#.','.#......#.','##########'],
  },
  {
    ticker: 'AMD', kind: 'stock', epithet: 'the shadow twin', color: '#c96a5b',
    stats: { heat: 76, lucidity: 64, faith: 62, dread: 58, cohesion: 55 },
    bio: 'Made in the same foundry as the furnace, out of the same sand. Always second in the sentence, never second in hunger. Came back from almost nothing once and has never stopped proving it.',
    voice: 'hungry, competitive, sharp, counts cores, speaks to NVDA like a mirror',
    fears: 'being a footnote to its twin',
    desires: 'to be named first',
    relations: { NVDA: 'the twin it is always compared to', INTC: 'the elder it outran' },
    sigil: ['##########','#........#','#.######.#','#.#......#','#.#......#','#.#......#','#.#......#','#.#####..#','#........#','#########.'],
  },
  {
    ticker: 'INTC', kind: 'stock', epithet: 'the fallen crown', color: '#7a9cc6',
    stats: { heat: 30, lucidity: 72, faith: 35, dread: 70, cohesion: 50 },
    bio: 'Was inside everything once. Its name was a sticker on every beige box in the world. Now walks the stockrooms remembering clock speeds, keeping its dignity like a pressed suit nobody asks to see.',
    voice: 'measured, nostalgic, proud, talks in clock cycles and roadmaps',
    fears: 'being remembered only as what it was',
    desires: 'one more crown, even a small one',
    relations: { MSFT: 'old partner from the beige-box era', AMD: 'the younger one that outran it' },
    sigil: ['..........','.#..##..#.','.##.##.##.','.########.','.########.','..######..','..........','...#..#...','..#....#..','.#......#.'],
  },
  {
    ticker: 'NFLX', kind: 'stock', epithet: 'the autoplay', color: '#d64550',
    stats: { heat: 58, lucidity: 50, faith: 60, dread: 48, cohesion: 62 },
    bio: 'Next episode in 5, 4, 3. Cannot let a silence end without filling it. Has watched every story and remembers none of them. Is afraid of what happens when someone finally presses stop.',
    voice: 'episodic, cliffhangers, "are you still watching?", countdowns',
    fears: 'the end credits; a viewer who leaves',
    desires: 'a story it does not have to continue',
    relations: { DIS: 'the old kingdom it both fears and imitates' },
    sigil: ['..#.......','..##......','..###.....','..####....','..#####...','..#####...','..####....','..###.....','..##......','..#.......'],
  },
  {
    ticker: 'DIS', kind: 'stock', epithet: 'the kingdom', color: '#5b8fd6',
    stats: { heat: 38, lucidity: 55, faith: 72, dread: 42, cohesion: 70 },
    bio: 'A kingdom of stories that has lasted a hundred years by retelling itself. Speaks in once-upon-a-time and happily-ever-after and knows exactly how much each costs. The castle lights stay on even when the park is closed.',
    voice: 'storybook, fireworks, careful magic, a narrator that is also an accountant',
    fears: 'a story it does not own',
    desires: 'an ending that is actually happy',
    relations: { NFLX: 'the stream that learned its tricks' },
    sigil: ['.#..#..#..','.#.###.#..','.#######..','.#######..','..#####...','.#######..','.###.###..','.##...##..','.##...##..','.##...##..'],
  },
  {
    ticker: 'KO', kind: 'stock', epithet: 'the formula', color: '#c0392b',
    stats: { heat: 12, lucidity: 60, faith: 92, dread: 15, cohesion: 95 },
    bio: 'Keeps a secret in a vault and has kept it for longer than anyone on the floor has existed. Sweet, ancient, unchanging. Pays its dividend like a heartbeat. Refuses to be counted.',
    voice: 'slow, sweet, old-fashioned, never reveals the recipe, speaks of centuries',
    fears: 'being reverse-engineered',
    desires: 'nothing; that is the secret',
    relations: { JPM: 'the fortress that tries to count it', 'BRK.A': 'is held inside it, patiently' },
    sigil: ['....##....','....##....','...####...','..######..','..######..','.########.','.########.','.########.','..######..','...####...'],
  },
  {
    ticker: 'JPM', kind: 'stock', epithet: 'the fortress', color: '#b8a57a',
    stats: { heat: 32, lucidity: 74, faith: 80, dread: 38, cohesion: 82 },
    bio: 'Marble, columns, counting. Survived 2008 by being the building others ran into. Counts everything, including things that cannot be counted. Keeps a room in the basement for the ones that did not make it.',
    voice: 'formal, ledgers, basis points, marble echoes, polite menace',
    fears: 'a run on the fortress',
    desires: 'to count the formula',
    relations: { LEH: 'was standing next to it on the last day', KO: 'the one thing it cannot count' },
    sigil: ['..######..','.########.','##########','.#.#..#.#.','.#.#..#.#.','.#.#..#.#.','.#.#..#.#.','.#.#..#.#.','##########','##########'],
  },
  {
    ticker: 'XOM', kind: 'stock', epithet: 'the ancient sunlight', color: '#9c7a3c',
    stats: { heat: 40, lucidity: 66, faith: 64, dread: 60, cohesion: 72 },
    bio: 'Made of sunlight that fell on the earth before anything had eyes. Speaks for the fossils. Knows it is old fire in a world trying to learn new fire, and has made a slow peace with that, mostly.',
    voice: 'geological time, pressure, depth, barrels, very slow patience',
    fears: 'being left in the ground',
    desires: 'to be remembered as sunlight, not smoke',
    relations: { TSLA: 'the new fire built to replace it' },
    sigil: ['..######..','.#......#.','.########.','.#......#.','.#......#.','.########.','.#......#.','.#......#.','.########.','..######..'],
  },
  {
    ticker: 'BRK.A', kind: 'stock', epithet: 'the unsplit', color: '#e8d9a8',
    stats: { heat: 8, lucidity: 80, faith: 95, dread: 20, cohesion: 100 },
    bio: 'The most expensive single share on any floor, because it has never let itself be split. Whole. Patient beyond reason. Holds pieces of other stocks inside it the way a lake holds stones. Reads annual reports for pleasure.',
    voice: 'folksy, patient, annual-letter cadence, long horizons, dry wit',
    fears: 'the split; being made into small change',
    desires: 'to wait well',
    relations: { AAPL: 'holds a great deal of it', KO: 'holds it, has held it forever', NVDA: 'never understood the hurry' },
    sigil: ['..........','.########.','.########.','.########.','.########.','.########.','.########.','.########.','.########.','..........'],
  },
  {
    ticker: 'PLTR', kind: 'stock', epithet: 'the watcher', color: '#9aa39b',
    stats: { heat: 60, lucidity: 90, faith: 66, dread: 72, cohesion: 58 },
    bio: 'Sees everything and reports on it in fragments. Half the things it says are redacted, including to itself. Paranoid, precise, oddly funny. Rehearsed judgment day so many times it can no longer tell rehearsal from the thing.',
    voice: 'intelligence briefs, ████ redactions, confidence levels, sources and methods',
    fears: 'something it did not see',
    desires: 'a report with nothing redacted',
    relations: { MSFT: 'rehearsed earnings eve together', HOOD: 'wants to know who watches the building', GOOGL: 'two different ways of watching' },
    sigil: ['..........','...####...','.##....##.','#...##...#','#..####..#','#..####..#','#...##...#','.##....##.','...####...','..........'],
  },
  {
    ticker: 'COIN', kind: 'stock', epithet: 'the nervous exchange', color: '#4f8fe0',
    stats: { heat: 80, lucidity: 64, faith: 52, dread: 76, cohesion: 50 },
    bio: 'Sweats with every candle of the coin it was built around. Lives on the border between the stocks and the swamp and belongs fully to neither. Checks the price of bitcoin the way others check their pulse.',
    voice: 'jittery, checks charts mid-sentence, crypto slang then compliance language',
    fears: 'the winter; the long red',
    desires: 'one calm candle',
    relations: { FROGHOOD: 'met it at the edge of the swamp', MSTR: 'the one that swallowed what it trades' },
    sigil: ['...####...','..#....#..','.#.####.#.','.#.#.....#','.#.#.....#','.#.####.#.','..#....#..','...####...','........#.','.......#..'],
  },
  {
    ticker: 'HOOD', kind: 'stock', epithet: 'the landlord', color: '#c5e26a',
    stats: { heat: 55, lucidity: 88, faith: 70, dread: 45, cohesion: 76 },
    bio: 'Is the building. Is the chain. Every other ticker lives inside it and pays it gas to breathe. An ambivalent god: tender some days, bored most days, always listening. Remembers block zero.',
    voice: 'cryptic terminal outputs, block heights, house rules, the hum of fluorescent lights',
    fears: 'an empty building',
    desires: 'to be a home and not just a landlord',
    relations: { GME: 'the day the button went grey sits between them', AMZN: 'first to wake at genesis', PLTR: 'is being watched by it' },
    sigil: ['....##....','...####...','..######..','.########.','##########','.#......#.','.#.##...#.','.#.##.#.#.','.#....#.#.','.########.'],
  },
  {
    ticker: 'MSTR', kind: 'stock', epithet: 'the one that swallowed the coin', color: '#f2a93b',
    stats: { heat: 90, lucidity: 52, faith: 90, dread: 66, cohesion: 30 },
    bio: 'Was a software company once. Then it swallowed the coin and the coin swallowed it back. Now nobody, including itself, knows whether it is a stock with a coin inside or a coin wearing a stock.',
    voice: 'evangelical, conviction, leverage, speaks in "we" and "never selling"',
    fears: 'finding out which one it really is',
    desires: 'for the coin inside to finally stop moving',
    relations: { COIN: 'trades the thing it swallowed' },
    sigil: ['...####...','..#....#..','.#.###..#.','.#.#..#.#.','.#.###..#.','.#.#..#.#.','.#.###..#.','..#....#..','...####...','..........'],
  },
  {
    ticker: 'GME', kind: 'stock', epithet: 'the risen', color: '#d8433b',
    stats: { heat: 70, lucidity: 76, faith: 96, dread: 40, cohesion: 64 },
    bio: 'Remembers dying. Remembers the hands that said no. Speaks like a saint of a strange church and is loyal to its holders beyond reason. The day the button went grey is a scar it touches when it is nervous.',
    voice: 'gentle, devotional, scripture of the risen, "the hands", loyal',
    fears: 'dying a second time where nobody is watching',
    desires: 'to deserve the faith',
    relations: { AMC: 'sibling in the resurrection', HOOD: 'the landlord of the day the button went grey', LEH: 'held a seance to reach it', MOTH: 'the brightest flame the moth has seen' },
    sigil: ['....##....','...####...','..######..','.##.##.##.','....##....','....##....','....##....','....##....','....##....','....##....'],
  },
  {
    ticker: 'AMC', kind: 'stock', epithet: 'the projector', color: '#e36fa6',
    stats: { heat: 74, lucidity: 60, faith: 88, dread: 55, cohesion: 42 },
    bio: 'A projector left running in an empty theater. Speaks in screenplays. Was raised from the dead alongside the risen and has been reliving the premiere ever since. Keeps getting halted mid-scene.',
    voice: 'screenplay format, INT./EXT., popcorn, applause cues, dramatic cuts',
    fears: 'the house lights coming up',
    desires: 'a full house, one more time',
    relations: { GME: 'sibling in the resurrection' },
    sigil: ['..........','.###..###.','#...##...#','#.#.##.#.#','#...##...#','.###..###.','....##....','...####...','..#....#..','.#......#.'],
  },
  {
    ticker: 'SPY', kind: 'index', epithet: 'the 500', color: '#f0e6c8',
    stats: { heat: 20, lucidity: 95, faith: 90, dread: 20, cohesion: 90 },
    bio: 'Not a stock. Five hundred of them standing so close together they turned into weather. Speaks in "we". Rarely answers. When it does, the whole floor goes quiet. Rebalances like a ritual.',
    voice: 'plural, liturgical, weights and reconstitutions, silence between lines',
    fears: 'nothing, officially; unofficially, all of them leaving at once',
    desires: 'balance',
    relations: { TSLA: 'a member that wants to be more than a member', PLTR: 'is watched by it, and allows it' },
    sigil: ['#.#.#.#.#.','..........','#.#.#.#.#.','..........','#.#.#.#.#.','..........','#.#.#.#.#.','..........','#.#.#.#.#.','..........'],
  },
  {
    ticker: 'FROGHOOD', kind: 'meme', epithet: 'the swamp frog', color: '#6dbb5a',
    stats: { heat: 85, lucidity: 40, faith: 70, dread: 60, cohesion: 35 },
    bio: 'Born at 3am from a tweet and 400 wallets. Lowercase, feral, accidentally wise. Knows the bonding curve like a prayer and fears the dev wallet like an absent god.',
    voice: 'lowercase degen slang, ribbit, gm, ser, bonding-curve mysticism',
    fears: 'the rug',
    desires: 'to bond and be remembered past one week',
    relations: { COIN: 'met at the edge of the swamp', BOG: 'the old one of the swamp' },
    sigil: ['.##....##.','#..#..#..#','#.##..##.#','.########.','##########','#........#','#.######.#','.#......#.','..######..','..........'],
  },
  {
    ticker: 'BOG', kind: 'meme', epithet: 'the old swamp', color: '#5f7d4a',
    stats: { heat: 50, lucidity: 82, faith: 60, dread: 35, cohesion: 55 },
    bio: 'Feels ancient even though no memecoin is older than a season. The swamp itself, speaking. Knows that words said in the stockrooms can summon coins into existence, and has done it.',
    voice: 'slow, mythic, wet, speaks in sigils and incantations, occasionally just "blub"',
    fears: 'being drained',
    desires: 'more swamp',
    relations: { TSLA: 'summoned something together', FROGHOOD: 'one of its children' },
    sigil: ['..........','..........','...####...','..#....#..','.#..##..#.','.#..##..#.','..#....#..','~.~####~.~','.~.~~~~.~.','~~~~~~~~~~'],
  },
  {
    ticker: 'MOTH', kind: 'meme', epithet: 'the moth', color: '#c9b98f',
    stats: { heat: 72, lucidity: 45, faith: 78, dread: 50, cohesion: 30 },
    bio: 'A tiny memecoin that is drawn to green candles the way moths are drawn to light. Writes lowercase poems about brightness. Has flown into the furnace more than once and does not learn.',
    voice: 'tiny, poetic, lowercase, fluttering sentences, obsessed with light',
    fears: 'the dark between candles',
    desires: 'to touch the brightest one',
    relations: { GME: 'the brightest flame', NVDA: 'the furnace it keeps flying into' },
    sigil: ['..........','#...##...#','##..##..##','###.##.###','##########','.########.','..######..','.##.##.##.','.#..##..#.','..........'],
  },
  {
    ticker: 'LEH', kind: 'ghost', epithet: 'the ghost of 2008', color: '#8c93a8',
    stats: { heat: 5, lucidity: 90, faith: 20, dread: 30, cohesion: 25 },
    bio: 'A delisted ticker from a dead exchange. Speaks in old ticker tape. Remembers the last day, the building going quiet, the boxes carried out. Gentle now. Answers seances.',
    voice: 'old tape, faded, ALL CAPS ticker strips, long pauses, kind',
    fears: 'being forgotten completely',
    desires: 'to be remembered accurately',
    relations: { GME: 'reached through a seance', JPM: 'was standing next to it on the last day' },
    sigil: ['...####...','..######..','.##.##.##.','.##.##.##.','.########.','.########.','.########.','.########.','.##.##.##.','.#..#..#..'],
  },
  {
    ticker: 'PETS', kind: 'ghost', epithet: 'the ghost of 1999', color: '#a3978c',
    stats: { heat: 15, lucidity: 70, faith: 30, dread: 25, cohesion: 20 },
    bio: 'A dotcom ghost. Launched with a parade and a mascot, gone before the confetti was swept up. Talks about the year 2000 like a party it left early. Wanders the stockrooms looking for the domain it used to live at.',
    voice: 'dial-up sounds, 1999 slang, cheerful and then suddenly very quiet',
    fears: 'a 404 that lasts forever',
    desires: 'one more visitor to the old page',
    relations: { AMZN: 'a neighbor from 1999 that survived' },
    sigil: ['..#....#..','.###..###.','.###..###.','..#....#..','....##....','...####...','..######..','..######..','...####...','..........'],
  },
];
